In [13]:
# ! pip install vllm

In [10]:
from datasets import load_dataset

dataset = load_dataset("naver-clova-ix/cord-v2")

dataset

DatasetDict({
    train: Dataset({
        features: ['image', 'ground_truth'],
        num_rows: 800
    })
    validation: Dataset({
        features: ['image', 'ground_truth'],
        num_rows: 100
    })
    test: Dataset({
        features: ['image', 'ground_truth'],
        num_rows: 100
    })
})

In [11]:
schema_dict = {
    "menu":
    {
        "nm": "name of the menu",
        "num": "identification number of menu",
        "unitprice": "unit price of menu",
        "cnt": "quantity of menu",
        "discountprice": "discounted price of menu",
        "price": "total price of menu",
        "itemsubtotal": "price of each menu after discount applied",
        "vatyn": "whether the price includes tax or not",
        "etc": "others",
        "sub": {
            "nm": "name of submenu",
            "unitprice": "unit price of submenu",
            "cnt": "quantity of submenu",
            "price": "total price of submenu",
            "etc": "others"
        }

    },
    "sub_total":
    {
        "price": "subtotal price",
        "discount_price": "discounted price in total",
        "service_price": "service charge",
        "othersvc_price": "added charge other than service charge",
        "tax_price": "tax amount",
        "etc": "others"
    },
    "total":
    {
        "total_price": "total price",
        "etc": "others",
        "cashprice": "amount of price paid in cash",
        "changeprice": "amount of change in cash",
        "creditcardprice": "amount of price paid in credit/debit card",
        "emoneyprice": "amount of price paid in emoney, point",
        "menutype_cnt": "total count of type of menu",
        "menuqty_cnt": "total count of quantity"
    }
}

In [12]:
import json
prompt = f"""You are a specialized in invoice and your role is to extract information from any invoice that is provided to you in the following valid json format. if the corresponding value is not present, leave the key with empty string.

{json.dumps(schema_dict)}

Fill the keys only when the information is available.
"""

In [13]:
prompt

'You are a specialized in invoice and your role is to extract information from any invoice that is provided to you in the following valid json format. if the corresponding value is not present, leave the key with empty string.\n\n{"menu": {"nm": "name of the menu", "num": "identification number of menu", "unitprice": "unit price of menu", "cnt": "quantity of menu", "discountprice": "discounted price of menu", "price": "total price of menu", "itemsubtotal": "price of each menu after discount applied", "vatyn": "whether the price includes tax or not", "etc": "others", "sub": {"nm": "name of submenu", "unitprice": "unit price of submenu", "cnt": "quantity of submenu", "price": "total price of submenu", "etc": "others"}}, "sub_total": {"price": "subtotal price", "discount_price": "discounted price in total", "service_price": "service charge", "othersvc_price": "added charge other than service charge", "tax_price": "tax amount", "etc": "others"}, "total": {"total_price": "total price", "etc": "others", "cashprice": "amount of price paid in cash", "changeprice": "amount of change in cash", "creditcardprice": "amount of price paid in credit/debit card", "emoneyprice": "amount of price paid in emoney, point", "menutype_cnt": "total count of type of menu", "menuqty_cnt": "total count of quantity"}}\n\nFill the keys only when the information is available.\n'

In [8]:
! pip install -Uqq "huggingface_hub"
from huggingface_hub import login
login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [14]:
from vllm import LLM

model_name = "srinathmkce/qwen-2.5-vl-7b-cord"


llm = LLM(
    model=model_name,
    max_model_len=4096,
    max_num_seqs=5,
    mm_processor_kwargs={
        "min_pixels": 28 * 28,
        "max_pixels": 1280 * 28 * 28,
        # "fps": 1,
    },
    # disable_mm_preprocessor_cache=args.disable_mm_preprocessor_cache,
)

INFO 03-11 18:51:28 __init__.py:207] Automatically detected platform cuda.
INFO 03-11 18:51:35 config.py:549] This model supports multiple tasks: {'classify', 'reward', 'score', 'generate', 'embed'}. Defaulting to 'generate'.
INFO 03-11 18:51:35 llm_engine.py:234] Initializing a V0 LLM engine (v0.7.3) with config: model='srinathmkce/qwen-2.5-vl-7b-cord', speculative_config=None, tokenizer='srinathmkce/qwen-2.5-vl-7b-cord', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=srinathmkce/qwen-2.5-vl-7b-cord, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=False, chunked_prefill_enabled=False, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs={'min_pixels': 784, 'max_pixels': 1003520}, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[8,4,2,1],"max_capture_size":8}, use_cached_outputs=False,
INFO 03-11 18:51:36 cuda.py:229] Using Flash Attention backend.
INFO 03-11 18:51:37 model_runner.py:1110] Starting to load model srinathmkce/qwen-2.5-vl-7b-cord...
WARNING 03-11 18:51:37 vision.py:94] Current `vllm-flash-attn` has a bug inside vision module, so we use xformers backend instead. You can run `pip install flash-attn` to use flash-attention backend.
INFO 03-11 18:51:37 config.py:3054] cudagraph sizes specified by model runner [1, 2, 4, 8] is overridden by config [8, 1, 2, 4]
INFO 03-11 18:51:37 weight_utils.py:254] Using model weights format ['*.safetensors']

Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]

INFO 03-11 18:51:40 model_runner.py:1115] Loading model weights took 15.5382 GB

Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.48, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
Keyword argument `min_pixels` is not a valid argument for this processor and will be ignored.
Keyword argument `max_pixels` is not a valid argument for this processor and will be ignored.
It looks like you are trying to rescale already rescaled images. If the input images have pixel values between 0 and 1, set `do_rescale=False` to avoid rescaling them again.

INFO 03-11 18:51:46 worker.py:267] Memory profiling takes 5.22 seconds
INFO 03-11 18:51:46 worker.py:267] the current vLLM instance can use total_gpu_memory (44.45GiB) x gpu_memory_utilization (0.90) = 40.00GiB
INFO 03-11 18:51:46 worker.py:267] model weights take 15.54GiB; non_torch_memory takes 0.06GiB; PyTorch activation peak memory takes 0.86GiB; the rest of the memory reserved for KV Cache is 23.54GiB.
INFO 03-11 18:51:46 executor_base.py:111] # cuda blocks: 27547, # CPU blocks: 4681
INFO 03-11 18:51:46 executor_base.py:116] Maximum concurrency for 4096 tokens per request: 107.61x
INFO 03-11 18:51:49 model_runner.py:1434] Capturing cudagraphs for decoding. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI. If out-of-memory error occurs during cudagraph capture, consider decreasing `gpu_memory_utilization` or switching to eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.

Capturing CUDA graph shapes: 100%|██████████| 4/4 [00:01<00:00,  2.30it/s]

INFO 03-11 18:51:51 model_runner.py:1562] Graph capturing finished in 2 secs, took 0.07 GiB
INFO 03-11 18:51:51 llm_engine.py:436] init engine (profile, create kv cache, warmup model) took 10.59 seconds

In [15]:
from vllm import SamplingParams

stop_token_ids = None
sampling_params = SamplingParams(temperature=0.1,
                                 max_tokens=1024,
                                 stop_token_ids=stop_token_ids)

In [16]:
import PIL

def create_vllm_messages(image_path, prompt):
    placeholder = "<|image_pad|>"
    vllm_prompt = ("<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n"
          f"<|im_start|>user\n<|vision_start|>{placeholder}<|vision_end|>"
          f"{prompt}<|im_end|>\n"
          "<|im_start|>assistant\n")

    image = PIL.Image.open(image_path)
    inputs = {
            "prompt": vllm_prompt,
            "multi_modal_data": {
                "image": image
            },
        }
    return inputs

In [17]:
create_vllm_messages("tests/test_0.png", prompt)

{'prompt': '<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n<|im_start|>user\n<|vision_start|><|image_pad|><|vision_end|>You are a specialized in invoice and your role is to extract information from any invoice that is provided to you in the following valid json format. if the corresponding value is not present, leave the key with empty string.\n\n{"menu": {"nm": "name of the menu", "num": "identification number of menu", "unitprice": "unit price of menu", "cnt": "quantity of menu", "discountprice": "discounted price of menu", "price": "total price of menu", "itemsubtotal": "price of each menu after discount applied", "vatyn": "whether the price includes tax or not", "etc": "others", "sub": {"nm": "name of submenu", "unitprice": "unit price of submenu", "cnt": "quantity of submenu", "price": "total price of submenu", "etc": "others"}}, "sub_total": {"price": "subtotal price", "discount_price": "discounted price in total", "service_price": "service charge", "othersvc_price": "added charge other than service charge", "tax_price": "tax amount", "etc": "others"}, "total": {"total_price": "total price", "etc": "others", "cashprice": "amount of price paid in cash", "changeprice": "amount of change in cash", "creditcardprice": "amount of price paid in credit/debit card", "emoneyprice": "amount of price paid in emoney, point", "menutype_cnt": "total count of type of menu", "menuqty_cnt": "total count of quantity"}}\n\nFill the keys only when the information is available.\n<|im_end|>\n<|im_start|>assistant\n',
 'multi_modal_data': {'image': <PIL.PngImagePlugin.PngImageFile image mode=RGB size=432x648>}}

In [18]:
import os
if not os.path.exists("tests"):
    os.mkdir("tests")

In [19]:
import json
from tqdm import tqdm

i = 0

ground_truth_list = []

batched_messages = []

for row in tqdm(dataset["test"]):

    # Save the image
    image = row["image"]
    image_path = os.path.join("tests", f"test_{i}.png")
    image.save(image_path)

    # save the ground truth information
    ground_truth = json.loads(row["ground_truth"])["gt_parse"]
    ground_truth_list.append(ground_truth)

    # create vllm prompt
    message = create_vllm_messages(image_path=image_path, prompt=prompt)
    batched_messages.append(message)
    
    i += 1

100%|██████████| 100/100 [00:52<00:00,  1.90it/s]

In [20]:
predictions = llm.generate(batched_messages, sampling_params=sampling_params)

WARNING 03-11 18:53:08 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:08 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:08 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:08 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:08 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:09 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:09 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:09 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:09 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:09 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:09 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:09 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:09 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:09 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:10 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:10 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:10 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:10 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:10 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:10 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:10 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:11 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:11 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:11 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:11 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:11 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:11 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:11 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:11 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:12 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:12 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:12 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:13 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:13 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:13 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:13 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:13 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:13 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:14 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:14 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:14 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:14 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:14 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:15 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:15 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:15 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:15 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:15 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:15 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:15 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:16 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:16 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:16 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:16 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:16 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:16 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:16 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:16 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:17 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:17 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:17 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:17 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:18 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:18 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:18 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:18 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:18 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:18 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:18 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:19 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:19 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:19 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:19 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:19 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:20 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:20 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:20 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:20 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:21 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:21 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:21 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:21 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:21 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:21 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:22 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:22 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:22 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:22 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:22 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:22 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:22 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:22 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:22 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:23 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:23 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:23 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:23 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:23 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:23 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}
WARNING 03-11 18:53:23 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}

Processed prompts: 100%|██████████| 100/100 [02:09<00:00,  1.29s/it, est. speed input: 1093.02 toks/s, output: 110.83 toks/s]

In [21]:
prediction_list = []

for prediction in predictions:
    result_text = prediction.outputs[0].text
    prediction_list.append(result_text)

In [26]:
prediction_list[3]

'{"menu": {"nm": "DONAT GULA", "unitprice": "@11000", "cnt": "1X", "price": "11,000"}, "sub_total": {"subtotal_price": "11,000"}, "total": {"total_price": "11,000", "cashprice": "11,000", "menuqty_cnt": "1.00xITEMS"}}'

In [27]:
ground_truth_list[3]

{'menu': {'nm': 'DONAT GULA',
  'unitprice': '@11000',
  'cnt': '1X',
  'price': '11,000'},
 'sub_total': {'subtotal_price': '11,000'},
 'total': {'total_price': '11,000',
  'cashprice': '11,000',
  'menuqty_cnt': '1.00xITEMs'}}

### Postprocess

In [28]:
def postprocess(text):
    parsed_text = ""
    try:
        parsed_text = json.loads(text.replace('```json', '').replace('```', ''))
        return parsed_text
    except:
        print(f"Unable to parse prediction text")

In [29]:
prediction_list = [postprocess(x) for x in prediction_list]

In [30]:
prediction_list[1]

{'menu': [{'nm': 'J.STB PROMO', 'price': '17500'},
  {'nm': 'Y.B.BAT', 'price': '46000'},
  {'nm': 'Y.BASO PROM', 'price': '27500'}],
 'total': {'total_price': '91000', 'cashprice': '91000'}}

### Evaluation - Accuracy

In [31]:
from collections import Counter

def flatten_dict(d, parent_key=""):
    items = {}
    for k, v in d.items():
        new_key = f"{parent_key}.{k}" if parent_key else k
        
        if isinstance(v, dict):  
            items.update(flatten_dict(v, new_key))
            
        elif isinstance(v, list):  
            if all(isinstance(i, dict) for i in v):
                for idx, item in enumerate(v):
                    items.update(flatten_dict(item, f"{new_key}[{idx}]"))
            else:
                items[new_key] = v
        else:
            items[new_key] = v

    return items

In [45]:
metrics_list = []
for i in range(len(prediction_list)):
    
    metrics_dict = {}
    gt = ground_truth_list[i]
    pred = prediction_list[i]

    if isinstance(gt["menu"], dict):
      gt["menu"] = [gt["menu"]]
    if isinstance(pred["menu"], dict):
      pred["menu"] = [pred["menu"]]
    
    gt_flat = flatten_dict(gt)
    pred_flat = flatten_dict(pred)

    total_keys = len(gt_flat)
    matched_keys = 0
    
    for key, gt_value in gt_flat.items():
        pred_value = pred_flat.get(key, "")
        if gt_value == pred_value:
            matched_keys += 1
        else:
            print(f"Ground Truth: {gt_value} , Prediction: {pred_value}")

    metrics_dict["invoice_no"] = i
    metrics_dict["total_keys"] = total_keys
    metrics_dict["matched_keys"] = matched_keys
    metrics_dict["accuracy"] = (matched_keys / total_keys ) * 100
    metrics_list.append(metrics_dict)

Ground Truth: -TICKET CP , Prediction: - TICKET CP
Ground Truth: 60.000 , Prediction:
Ground Truth: 60.000 , Prediction:
Ground Truth: 5.455 , Prediction: 5,455
Ground Truth: 60.000 , Prediction: 60,000
Ground Truth: JASMINE MT ( L ) , Prediction: JASMINE MT (L)
Ground Truth: COCONUT JELLY ( L ) , Prediction:
Ground Truth: 4,000 , Prediction:
Ground Truth: 1.00xITEMs , Prediction: 1.00xITEMS
Ground Truth: 1.00 , Prediction:
Ground Truth: CHOCO CUS ARD PASTRY , Prediction: CHOCO CUSARD PASTRY
Ground Truth: Bumbu Kaldu Ayam 1 , Prediction: Bumbu Kaldu Ayam
Ground Truth: 120,000 , Prediction:
Ground Truth: @880 , Prediction: @880 100%
Ground Truth: 100% , Prediction:
Ground Truth: 0 , Prediction:
Ground Truth: (2 , Prediction: 2
Ground Truth: 3,000 , Prediction: 3.000
Ground Truth: 3,000 , Prediction: 3.000
Ground Truth: ['46.636', '46.636'] , Prediction: 46.636
Ground Truth: 17,850 , Prediction: 17,650
Ground Truth: IVANGGO , Prediction: MANGGO
Ground Truth: IVINERAL WATER (bundling) 5k , Prediction:
Ground Truth: 1 , Prediction:
Ground Truth: 4,545 , Prediction:
Ground Truth: Plastik Amook , Prediction: Plastik Amok
Ground Truth: 156000 , Prediction:
Ground Truth: [MD] SOFT STEAMED CHEESEC , Prediction: SOFT STEAMED CHEESEC
Ground Truth: 2 , Prediction: 2 [MD]
Ground Truth: [MD] SOFT STEAMED CHOCOCA , Prediction: SOFT STEAMED CHOCOCA
Ground Truth: 2 , Prediction: 2 [MD]
Ground Truth: Rp.56.000 , Prediction: Rp. 56.000
Ground Truth: Rp.56.000 , Prediction: Rp. 56.000
Ground Truth: Rp.62.000 , Prediction: Rp. 62.000
Ground Truth: Rp.62.000 , Prediction: Rp. 62.000
Ground Truth: Rp.0 , Prediction: Rp. 0
Ground Truth: Rp.0 , Prediction: Rp. 0
Ground Truth: Rp.118.000 , Prediction: Rp. 118.000
Ground Truth: Nasi Cap Cay Porsi B esar , Prediction: Nasi Cap Cay Porst B
Ground Truth: Cap Cay , Prediction:
Ground Truth: Minuman , Prediction:
Ground Truth: Lain-lain , Prediction:
Ground Truth: 61,600 , Prediction:
Ground Truth: ABURA UDON SPICY , Prediction: :-ABURA UDON SPICY
Ground Truth: GRILLED BABY POTATO (R , Prediction: GRILLED BABY POTATO ( R
Ground Truth: 20.000 , Prediction:
Ground Truth: DF Fish Fillet Garlc , Prediction: DF Fish Fillet Garlic
Ground Truth: LUNCH BOX 3P SET W/RED BAG & SP00 N. , Prediction: HPL754DR LUNCH BOX 3P SET W/RED BAG & SPOON
Ground Truth: HPL754DR , Prediction:
Ground Truth: 8 , Prediction: 8 PCS
Ground Truth: 1,555,200 , Prediction:
Ground Truth: RICE CASE 7L W/CUP , Prediction: HPL500 RICE CASE 7L W/CUP
Ground Truth: HPL500 , Prediction:
Ground Truth: 5 , Prediction: 5 PCS
Ground Truth: 780,000 , Prediction:
Ground Truth: LUNCH BOX 3P SET W/BLACK BAG & SP OON , Prediction: HPL754DB LUNCH BOX 3P SET W/BLACK BAG & SPOON
Ground Truth: HPL754DB , Prediction:
Ground Truth: 4 , Prediction: 4 PCS
Ground Truth: 777,600 , Prediction:
Ground Truth: 3,112,800 , Prediction:
Ground Truth: 3 , Prediction:
Ground Truth: 17 , Prediction:
Ground Truth: Bakery Aneka Sisir Banana,Pizza,yoko,Mar mer,Daging,abon,keju,cokelat,dll , Prediction: Bakery Aneka Sisir banana,Pizza,yoko,Mar mer,Daging,abon,keju,cokelat,dll
Ground Truth: Chicken HCC. 1Pcs , Prediction: Chicken HCC, 1Pcs
Ground Truth: 15.000 , Prediction: 15,000
Ground Truth: 6 , Prediction: 6 Pcs
Ground Truth: 88,000 , Prediction: 88.000
Ground Truth: 45,000.00 , Prediction:
Ground Truth: 0.00 , Prediction:
Ground Truth: 18,000.00 , Prediction:
Ground Truth: Superice Cauburry , Prediction: Caudburry
Ground Truth: (TA) NASI GRG TERI MEDAN , Prediction: (TA) NASI URG TERI MEDAN
Ground Truth: 30,365 , Prediction:
Ground Truth: 334,011 , Prediction: 11
Ground Truth: -11 , Prediction:
Ground Truth: ['100,000', '100,000'] , Prediction: 100,000
Ground Truth: Kepiting 7-8.4ons - Chilly 0.7 1 , Prediction: Kepiting 7-8.4ons - Chilly 0.7
Ground Truth: Udang Telur Asin - Regular , Prediction: Kailan 2 Rasa
Ground Truth: 47,500 , Prediction: 45,000
Ground Truth: Kailan 2 Rasa , Prediction: Mantau - 2 pcs
Ground Truth: 45,000 , Prediction: 25,000
Ground Truth: Mantau - 2 pcs , Prediction: Sweet Tea
Ground Truth: 1 , Prediction: 2
Ground Truth: 25,000 , Prediction: 16,000
Ground Truth: Sweet Tea , Prediction: Nasi Putih
Ground Truth: 2 , Prediction: 7
Ground Truth: 16,000 , Prediction: 42,000
Ground Truth: Nasi Putih , Prediction: Mantau - 3 pcs
Ground Truth: 7 , Prediction: 1
Ground Truth: 42,000 , Prediction: 37,500
Ground Truth: Mantau - 3 pcs , Prediction:
Ground Truth: 1 , Prediction:
Ground Truth: 37,500 , Prediction:
Ground Truth: Bola Ubi Mini Original (14 Pcs ) , Prediction: Bola Ubi Mini Original (14 Pcs)
Ground Truth: 1x , Prediction: 1X
Ground Truth: -2 600 , Prediction: -2,600
Ground Truth: AREM - AREM , Prediction: AREM AREM
Ground Truth: 8000 , Prediction: 3000
Ground Truth: 9000 , Prediction: 3000
Ground Truth: -7.200 , Prediction: -7,200
Ground Truth: 2,000 , Prediction: 2.000
Ground Truth: Kopi Susu Kampung Less Ice , Prediction: Kopi Susu Kampung - Less Ice
Ground Truth: 1 , Prediction:
Ground Truth: CHEESE JOHN , Prediction: 2095-CHEESE JOHN
Ground Truth: 2005- , Prediction:
Ground Truth: 20,000 , Prediction: 50,000
Ground Truth: 50,000 , Prediction: 30,000
Ground Truth: 30,000 , Prediction:
Ground Truth: =*LARGE*== , Prediction: AYM GR JUN NJAN
Ground Truth: 2 , Prediction: 1
Ground Truth: AYM GR JUN NJAN , Prediction: SAPO TH SEAFOOD
Ground Truth: 108,000 , Prediction: 172,000
Ground Truth: =*MEDIUM*= , Prediction: =*LARGE*==
Ground Truth: SAPO TH SEAFOOD , Prediction: POCAI 3
Ground Truth: 1 , Prediction: 2
Ground Truth: 172,000 , Prediction: 222,000
Ground Truth: =*LARGE*== , Prediction: =*MEDIUM*=
Ground Truth: POCAI 3 , Prediction: GURAME FILLET M ASAM MANIS
Ground Truth: 111,000 , Prediction:
Ground Truth: 2 , Prediction: 1
Ground Truth: 222.000 , Prediction: 163,000
Ground Truth: =*MEDIUM*= , Prediction: BIHUN GORENG JJ
Ground Truth: 2 , Prediction: 1
Ground Truth: GURAME FILLET M , Prediction: ICED TEA
Ground Truth: 1 , Prediction: 5
Ground Truth: 163,000 , Prediction: 60,000
Ground Truth: ASAM MANIS , Prediction:
Ground Truth: BIHUN GORENG JJ , Prediction: NASI PUTIH
Ground Truth: 1 , Prediction: 7
Ground Truth: 116,000 , Prediction: 70,000
Ground Truth: =*LARGE*== , Prediction:
Ground Truth: ICED TEA , Prediction:
Ground Truth: 12,000 , Prediction:
Ground Truth: 5 , Prediction:
Ground Truth: 60,000 , Prediction:
Ground Truth: NASI PUTIH , Prediction:
Ground Truth: 10,000 , Prediction:
Ground Truth: 7 , Prediction:
Ground Truth: 70,000 , Prediction:
Ground Truth: 198000 , Prediction:
Ground Truth: *110000 , Prediction:
Ground Truth: 50 - , Prediction:
Ground Truth: 25,000 , Prediction: 25.000
Ground Truth: 25.000 , Prediction: 25,000
Ground Truth: 2.000 , Prediction: 2,000
Ground Truth: @ 12.000 , Prediction: @12.000
Ground Truth: @ 12.000 , Prediction: @12.000
Ground Truth: ['159.500', '20.000'] , Prediction:
Ground Truth: PHOTAI CHIN , Prediction: PHO TAI CHIN
Ground Truth: Pedas sedikit , Prediction: - Pedas sedikit
Ground Truth: BAKSO BNGKS , Prediction: BAKSO BNKS
Ground Truth: 15.000 , Prediction: 15,000
Ground Truth: 6 , Prediction: 8
Ground Truth: 6.000 , Prediction: 6,000
Ground Truth: 21.000 , Prediction: 21,000
Ground Truth: 30.000 , Prediction: 30,000
Ground Truth: 9.000 , Prediction: 9,000
Ground Truth: 240.000 , Prediction: 240,000
Ground Truth: 250.000 , Prediction: 250,000
Ground Truth: (Qty=4.00) , Prediction: 4.00
Ground Truth: PHO TAI CHIN(R) , Prediction: PHO TAI CHIN (R)
Ground Truth: ['62,000', '201'] , Prediction: 62,000
Ground Truth: 1 , Prediction:
Ground Truth: SATE ATI GO , Prediction: SATECATIGO
Ground Truth: BLACK PAPPER MEATBALL PAS , Prediction: BLACK PEPPER MEATBALL PAS

In [33]:
import pandas as pd

metrics_df = pd.DataFrame(metrics_list)

metrics_df.round(2)

    invoice_no  total_keys  matched_keys  accuracy
0            0          11             6     54.55
1            1           8             8    100.00
2            2          10             7     70.00
3            3           8             7     87.50
4            4          14            14    100.00
..         ...         ...           ...       ...
95          95          12            11     91.67
96          96          11            10     90.91
97          97          13            12     92.31
98          98          13            12     92.31
99          99          29            29    100.00

[100 rows x 4 columns]

In [34]:
metrics_df["accuracy"].mean()

89.0893754261502

### Evaluation - Precision and Recall

In [35]:
def extract_values(data, level, key):
    values = []
    if level == "sub" and isinstance(data, dict) and "sub" in data["menu"]:
      menu = data["menu"]
    else:
      menu = data.get(level, [])
    if isinstance(menu, dict):
        if key in menu:
            values.append(menu[key])
    else:
        for item in menu:
            if key in item:
                values.append(item[key])

    return values

In [36]:
keys_to_evaluate = []

keys = ["menu", "sub", "sub_total", "total"]

for k in keys:
    if k == "sub":
        d = schema_dict["menu"][k]
    else:
        d = schema_dict[k]

    for k1 in d.keys():
        keys_to_evaluate.append(f"{k}.{k1}")

print(keys_to_evaluate)

['menu.nm', 'menu.num', 'menu.unitprice', 'menu.cnt', 'menu.discountprice', 'menu.price', 'menu.itemsubtotal', 'menu.vatyn', 'menu.etc', 'menu.sub', 'sub.nm', 'sub.unitprice', 'sub.cnt', 'sub.price', 'sub.etc', 'sub_total.price', 'sub_total.discount_price', 'sub_total.service_price', 'sub_total.othersvc_price', 'sub_total.tax_price', 'sub_total.etc', 'total.total_price', 'total.etc', 'total.cashprice', 'total.changeprice', 'total.creditcardprice', 'total.emoneyprice', 'total.menutype_cnt', 'total.menuqty_cnt']

In [37]:
from collections import Counter


def compute_metrics(gt_values, pred_values):
    """Computes Precision, Recall, F1-score, and Accuracy for exact matches."""

    gt_counter = Counter(gt_values)
    pred_counter = Counter(pred_values)

    tp = 0  # True Positives (Correct Matches)
    fp = 0  # False Positives (Extra Predictions)
    fn = 0  # False Negatives (Missing Predictions)

    matched_pred = set()

    # Exact Matches
    for val in gt_counter:
        if val in pred_counter:
            tp += min(gt_counter[val], pred_counter[val])  # Count matches
            matched_pred.add(val)

    # Compute FP (Extra Predictions not in GT)
    fp = sum(pred_counter[val] for val in pred_counter if val not in matched_pred)

    # Compute FN (Missing Predictions in GT)
    fn = sum(gt_counter[val] for val in gt_counter if val not in matched_pred)

    return {"tp": tp, "fp": fp, "fn": fn}

In [38]:
i = 0

metrics = {key: {"tp": 0, "fp": 0, "fn": 0, "total_gt": 0} for key in keys_to_evaluate}
for gt, pred in zip(ground_truth_list, prediction_list):
    for key in keys_to_evaluate:
        level, sub_level = key.split('.')
        gt_values = extract_values(data=gt, level=level, key=sub_level)
        pred_values = extract_values(data=pred, level=level, key=sub_level)
        # print(key, gt_values, pred_values)

        gt_values = [str(x) for x in gt_values]
        pred_values = [str(x) for x in pred_values]

        # compute the precision, recall and f1-score for the key    
        instance_metrics = compute_metrics(gt_values, pred_values)
        # print(key, instance_metrics)

        metrics[key]["tp"] += instance_metrics["tp"]
        metrics[key]["fp"] += instance_metrics["fp"]
        metrics[key]["fn"] += instance_metrics["fn"]
        metrics[key]["total_gt"] += len(gt_values)

In [39]:
final_metrics = []

for key, value in metrics.items():
    tp, fp, fn, total_gt = value["tp"], value["fp"], value["fn"], value["total_gt"]

    # precision
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0

    # Recall
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0

    # F1-score
    f1_score = ( 2 * precision * recall) / (precision + recall) if (precision + recall) > 0 else 0

    # Accuracy
    accuracy = tp / total_gt if total_gt > 0 else 0

    final_metrics.append({
        "key" : key,
        "precision" : precision,
        "recall" : recall,
        "f1-score" : f1_score,
        "tp" : tp,
        "total_gt": total_gt,
        "accuracy" : accuracy
    })

In [40]:
final_metrics_df = pd.DataFrame(final_metrics)

final_metrics_df[final_metrics_df["total_gt"] > 0]

,key,precision,recall,f1-score,tp,total_gt,accuracy
0,menu.nm,0.887097,0.876494,0.881764,220,251,0.876494
1,menu.num,1.000000,0.636364,0.777778,7,11,0.636364
2,menu.unitprice,0.846154,0.820896,0.833333,55,67,0.820896
3,menu.cnt,0.962791,0.958333,0.960557,207,220,0.940909
4,menu.discountprice,0.444444,0.571429,0.500000,4,7,0.571429
5,menu.price,0.947581,0.955285,0.951417,235,246,0.955285
6,menu.itemsubtotal,0.000000,0.000000,0.000000,0,6,0.000000
8,menu.etc,0.000000,0.000000,0.000000,0,3,0.000000
9,menu.sub,0.666667,0.727273,0.695652,16,22,0.727273
16,sub_total.discount_price,0.750000,1.000000,0.857143,6,6,1.000000
17,sub_total.service_price,0.916667,0.916667,0.916667,11,12,0.916667
19,sub_total.tax_price,0.976190,0.953488,0.964706,41,43,0.953488
20,sub_total.etc,0.625000,0.714286,0.666667,5,7,0.714286
21,total.total_price,0.906250,0.915789,0.910995,87,95,0.915789
23,total.cashprice,0.907692,0.880597,0.893939,59,67,0.880597
24,total.changeprice,0.928571,0.928571,0.928571,52,56,0.928571
25,total.creditcardprice,1.000000,0.937500,0.967742,15,16,0.937500
26,total.emoneyprice,0.500000,1.000000,0.666667,1,1,1.000000
27,total.menutype_cnt,1.000000,0.571429,0.727273,4,7,0.571429
28,total.menuqty_cnt,0.827586,0.827586,0.827586,24,29,0.827586

### Inference Pipeline

1. Create a simple web interface
2. Save the image
3. Use the existing prompt
4. create vllm prompt
5. initialize the llm
6. initialize the sampling parameters
7. perform prediction
8. extract the output

In [60]:
# ! pip install gradio

In [63]:
import os
if not os.path.exists("inference"):
    os.mkdir("inference")

In [64]:
import json
prompt = f"""You are a specialized in invoice and your role is to extract information from any invoice that is provided to you in the following valid json format. if the corresponding value is not present, leave the key with empty string.

{json.dumps(schema_dict)}

Fill the keys only when the information is available.
"""

In [ ]:
from vllm import LLM

model_name = "srinathmkce/qwen-2.5-vl-7b-cord"


llm = LLM(
    model=model_name,
    max_model_len=4096,
    max_num_seqs=5,
    mm_processor_kwargs={
        "min_pixels": 28 * 28,
        "max_pixels": 1280 * 28 * 28,
        # "fps": 1,
    },
    # disable_mm_preprocessor_cache=args.disable_mm_preprocessor_cache,
)

In [65]:
from vllm import SamplingParams

stop_token_ids = None
sampling_params = SamplingParams(temperature=0.1,
                                 max_tokens=1024,
                                 stop_token_ids=stop_token_ids)

In [67]:
import gradio as gr
from PIL import Image
import io
def invoice_parser(image):
    image_path = os.path.join("inference", "test_image.png")
    image.save(image_path)

    vllm_prompt = create_vllm_messages(image_path=image_path, prompt=prompt)

    prediction = llm.generate([vllm_prompt], sampling_params=sampling_params)

    return prediction[0].outputs[0].text
    

def reset_fields():
    """Resets both the image and parsed output."""
    return None, None

# Define Gradio UI
with gr.Blocks() as demo:
    with gr.Row():
        with gr.Column(scale=1):
            gr.Markdown("### Upload Invoice")
            image_input = gr.Image(type="pil", label="Invoice Image")
            submit_btn = gr.Button("Submit")
            reset_btn = gr.Button("Reset")  # Reset Button

        with gr.Column(scale=1):
            gr.Markdown("### Parsed Invoice Details")
            output_text = gr.JSON(label="Extracted Data")

    # Define button functionalities
    submit_btn.click(fn=invoice_parser, inputs=image_input, outputs=output_text)
    reset_btn.click(fn=reset_fields, inputs=[], outputs=[image_input, output_text])  # Reset both panes

# Launch app
demo.launch(share=True)

* Running on local URL:  http://127.0.0.1:7871
* Running on public URL: https://25ef71fe05293616d2.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

WARNING 03-11 19:48:42 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.35s/it, est. speed input: 481.12 toks/s, output: 29.55 toks/s]

WARNING 03-11 19:49:38 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}

Processed prompts: 100%|██████████| 1/1 [00:03<00:00,  3.08s/it, est. speed input: 516.31 toks/s, output: 29.28 toks/s]

WARNING 03-11 19:50:29 utils.py:1445] The following intended overrides are not keyword-only args and and will be dropped: {'min_pixels', 'max_pixels'}

Processed prompts: 100%|██████████| 1/1 [00:04<00:00,  4.66s/it, est. speed input: 346.28 toks/s, output: 30.50 toks/s]